<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>F5 iRule</string>
	<key>fileTypes</key>
	<array>
		<string>irule</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^.*\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}.*$</string>
	<key>keyEquivalent</key>
	<string>^~I</string>
	<key>name</key>
	<string>iRule</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.irule</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.constant.</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.irule</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>match any HTTP::command type message</string>
			<key>match</key>
			<string>\b([A-Z_]+)::([^\s]+)\b</string>
			<key>name</key>
			<string>meta.class.irule</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.when.irule</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.irule</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>match a when SOMETHING</string>
			<key>match</key>
			<string>(when)\s+([A-Z_]+)</string>
			<key>name</key>
			<string>meta.function.irule</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b</string>
			<key>name</key>
			<string>constant.ipv4.irule</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bPool_[^\s]+\b</string>
			<key>name</key>
			<string>constant.pool.irule</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]+)|([0-9]+(\.[0-9]+)?))\b</string>
			<key>name</key>
			<string>constant.numeric.irule</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.irule</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.irule</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.irule</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]?|37[0-7]?|[4-7][0-7]?|.)</string>
					<key>name</key>
					<string>constant.character.escape.irule</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.irule</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.irule</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.irule</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]|37[0-7]?|[4-7][0-7]?|.)</string>
					<key>name</key>
					<string>constant.character.escape.irule</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.irule</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(#).*$\n?</string>
			<key>name</key>
			<string>comment.line.hash.irule</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(else|if|elseif|return)\b</string>
			<key>name</key>
			<string>keyword.control.irule</string>
		</dict>
		<dict>
			<key>match</key>
			<string>!|\$|%|&amp;|\*|\-\-|\-|\+\+|\+|~|===|==|=|!=|!==|&lt;=|&gt;=|&lt;&lt;=|&gt;&gt;=|&gt;&gt;&gt;=|&lt;&gt;|&lt;|&gt;|!|&amp;&amp;|\|\||\?\:|\*=|(?&lt;!\()/=|%=|\+=|\-=|&amp;=|\^=|\b(in|instanceof|new|delete|typeof|void)\b</string>
			<key>name</key>
			<string>keyword.operator.irule</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.when.irule</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.name.irule</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(set)\s+([^\s]+)\s+</string>
			<key>name</key>
			<string>meta.declaration.var</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.irule</string>
	<key>uuid</key>
	<string>9636BEB3-DA81-4D9A-9030-E5A662CFCD1F</string>
</dict>
</plist>
